/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Professor
 */
public class QuizView extends javax.swing.JFrame {

    /**
     * Creates new form QuizView
     */
    public QuizView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnGrupo1 = new javax.swing.ButtonGroup();
        btnGrupo2 = new javax.swing.ButtonGroup();
        btnGrupo3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rd1A = new javax.swing.JRadioButton();
        rd1B = new javax.swing.JRadioButton();
        rd1C = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rd2A = new javax.swing.JRadioButton();
        rd2B = new javax.swing.JRadioButton();
        rd2C = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rd3A = new javax.swing.JRadioButton();
        rd3B = new javax.swing.JRadioButton();
        rd3C = new javax.swing.JRadioButton();
        btnConcluir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quiz"));

        jLabel1.setText("O que é Java?");

        btnGrupo1.add(rd1A);
        rd1A.setText("Um banco de dados");

        btnGrupo1.add(rd1B);
        rd1B.setText("Uma linguagem de programação");

        btnGrupo1.add(rd1C);
        rd1C.setText("Uma IDE");

        jLabel2.setText("O que é SQL?");

        btnGrupo2.add(rd2A);
        rd2A.setText("Um programa de banco de dados");

        btnGrupo2.add(rd2B);
        rd2B.setText("Um SGBD");

        btnGrupo2.add(rd2C);
        rd2C.setText("Uma linguagem de banco de dados");

        jLabel3.setText("Qual arquitetura de projeto estamos usando?");

        btnGrupo3.add(rd3A);
        rd3A.setText("Hierárquica");

        btnGrupo3.add(rd3B);
        rd3B.setText("MVC");

        btnGrupo3.add(rd3C);
        rd3C.setText("Singleton");

        btnConcluir.setText("Concluir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd3C)
                    .addComponent(rd3B)
                    .addComponent(rd3A)
                    .addComponent(rd2C)
                    .addComponent(rd2B)
                    .addComponent(rd1C)
                    .addComponent(rd1B)
                    .addComponent(jLabel1)
                    .addComponent(rd1A)
                    .addComponent(jLabel2)
                    .addComponent(rd2A)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConcluir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd1A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd1C)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd2A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd2C)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd3C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluir;
    private javax.swing.ButtonGroup btnGrupo1;
    private javax.swing.ButtonGroup btnGrupo2;
    private javax.swing.ButtonGroup btnGrupo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rd1A;
    private javax.swing.JRadioButton rd1B;
    private javax.swing.JRadioButton rd1C;
    private javax.swing.JRadioButton rd2A;
    private javax.swing.JRadioButton rd2B;
    private javax.swing.JRadioButton rd2C;
    private javax.swing.JRadioButton rd3A;
    private javax.swing.JRadioButton rd3B;
    private javax.swing.JRadioButton rd3C;
    // End of variables declaration//GEN-END:variables
}
