/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import model.ContaModel;

/**
 *
 * @author Professor
 */
public class ContaView extends javax.swing.JFrame {

    private final ContaModel model;
    /**
     * Creates new form ContaView
     */
    public ContaView(ContaModel model) {
        initComponents();
        this.model = model;
    }
    
    public void adicionarBotaoOKListener(ActionListener evento) {
        btnOK.addActionListener(evento);
    } // fecha adicionarBotaoOKListener
    
    public void atualizarModel() {
//        ButtonModel btnModel = btnGrupoConta.getSelection();
//        
//        if (btnModel == rdCorrente.getModel()) {
//            model.setTipo("Corrente");
//        }
//        else if (btnModel == rdPoupanca.getModel()) {
//            model.setTipo("Poupança");
//        }
//        else if (btnModel == rdSalario.getModel()) {
//            model.setTipo("Salário");
//        }
        // Usando ifs
        
        String tipo = btnGrupoConta.getSelection().getActionCommand();
        model.setTipo(tipo);
        
        model.setCartaoCredito(chkCartaoCredito.isSelected());
        model.setSeguroCartao(chkSeguroCartao.isSelected());
        model.setTalaoCheques(chkTalaoCheques.isSelected());
    } // fecha atualizarModel
    
    public void mostrarMensagem() {
        JOptionPane.showMessageDialog(this, model);
    } // fecha mos
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNINGtrarMensagem
: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoConta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdCorrente = new javax.swing.JRadioButton();
        rdPoupanca = new javax.swing.JRadioButton();
        rdSalario = new javax.swing.JRadioButton();
        btnOK = new javax.swing.JButton();
        chkCartaoCredito = new javax.swing.JCheckBox();
        chkSeguroCartao = new javax.swing.JCheckBox();
        chkTalaoCheques = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        btnGrupoConta.add(rdCorrente);
        rdCorrente.setText("Conta corrrente");
        rdCorrente.setActionCommand("Corrente");

        btnGrupoConta.add(rdPoupanca);
        rdPoupanca.setText("Conta poupança");
        rdPoupanca.setActionCommand("Poupança");

        btnGrupoConta.add(rdSalario);
        rdSalario.setText("Conta salário");
        rdSalario.setActionCommand("Salário");

        btnOK.setText("OK");

        chkCartaoCredito.setText("Cartão de crédito");

        chkSeguroCartao.setText("Seguro do cartão");

        chkTalaoCheques.setText("Talão de cheques");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdCorrente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdPoupanca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdSalario))
                            .addComponent(chkCartaoCredito)
                            .addComponent(chkSeguroCartao)
                            .addComponent(chkTalaoCheques))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdCorrente)
                    .addComponent(rdPoupanca)
                    .addComponent(rdSalario))
                .addGap(18, 18, 18)
                .addComponent(chkCartaoCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSeguroCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTalaoCheques)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupoConta;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox chkCartaoCredito;
    private javax.swing.JCheckBox chkSeguroCartao;
    private javax.swing.JCheckBox chkTalaoCheques;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdCorrente;
    private javax.swing.JRadioButton rdPoupanca;
    private javax.swing.JRadioButton rdSalario;
    // End of variables declaration//GEN-END:variables
}
